### ISSUE TITLE
I think there's an error in my user information

### ISSUE THREAD

**Issue by teetree0624** [farcasterxyz/fname-registry#263]
I think your username is invalid Can I get some help
![1000000474](https://github.com/farcasterxyz/fname-registry/assets/171658966/376b5b6d-8532-4594-8537-913ec421dbaa)
![1000000472](https://github.com/farcasterxyz/fname-registry/assets/171658966/4e449f5e-1a1c-4ab1-af71-f033bf29aba2)

**Comment by teetree0624** [comment]
my FID is 534167 and username is teetree0624

**Comment by sds** [comment]
Hey, we aren't responsible for those dashboards you're linking. Please reach out to whoever manages those.

I can confirm that our hubs show your username as teetree0624.

```
> r = await rpcClient.getUserNameProofsByFid({ fid: 534167 });
Ok { value: { proofs: [ [Object] ] } }
> r.value.proofs
[
  {
    timestamp: 1715592926,
    name: <Buffer 74 65 65 74 72 65 65 30 36 32 34>,
    owner: <Buffer f9 7c 3e 7a 47 2b bc 83 65 50 60 a4 d9 bf 5d 7d 61 e9 54 74>,
    signature: <Buffer d8 a9 ce d7 8b de 7f ba c5 57 fe 27 0a 41 5a dc 89 8d 55 6a e7 32 ae db f3 ac 32 67 07 e5 47 7f 11 bb 68 7a 8e 9d 82 9b 13 12 05 85 48 65 d9 4e cc d6 ... 15 more bytes>,
    fid: 534167,
    type: 1
  }
]
> r.value.proofs[0].name.toString()
'teetree0624'
```

**Comment by teetree0624** [comment]
Thank you for looking into the problem. I did it because my support team
ignored my multiple emails for weeks on end. Sorry for leaving the message
in the wrong place.

2024년 6월 10일 (월) 오전 8:27, Shane da Silva ***@***.***>님이 작성:
